# Generated by Django 4.1.5 on 2023-06-23 09:31

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adminuser',
            fields=[
                ('emailid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, max_length=10, null=True)),
            ],
            managers=[
                ('Objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='appusers',
            fields=[
                ('usercode', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=30, null=True)),
                ('emailid', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('regdate', models.DateField(blank=True, null=True)),
                ('password', models.CharField(blank=True, max_length=10, null=True)),
            ],
            managers=[
                ('Objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='book',
            fields=[
                ('emailiduploadedby', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('uploadeddate', models.DateField(blank=True, null=True)),
                ('title', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=30)),
                ('bookcode', models.AutoField(primary_key=True, serialize=False)),
                ('bookfilename', models.CharField(max_length=30)),
                ('bookdesc', models.CharField(max_length=500)),
                ('audiofilename', models.CharField(max_length=30)),
                ('imagefilename', models.CharField(max_length=50)),
            ],
            managers=[
                ('Objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='genre',
            fields=[
                ('genrename', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
            managers=[
                ('Objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='userprogress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startedon', models.DateField(blank=True, null=True)),
                ('chaptercompleted', models.IntegerField(blank=True, null=True)),
                ('bookcode', models.ForeignKey(blank=True, db_column='bookcode', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='firstapp.book')),
                ('usercode', models.ForeignKey(blank=True, db_column='usercode', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='firstapp.appusers')),
            ],
            managers=[
                ('Objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedbackdate', models.DateField(blank=True, null=True)),
                ('feedback', models.CharField(blank=True, max_length=100, null=True)),
                ('bookcode', models.ForeignKey(blank=True, db_column='bookcode', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='firstapp.book')),
                ('useremailid', models.ForeignKey(blank=True, db_column='emailid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='firstapp.appusers')),
            ],
            managers=[
                ('Objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='chapters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapterno', models.IntegerField(blank=True, null=True)),
                ('bookcode', models.ForeignKey(blank=True, db_column='bookcode', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='firstapp.book')),
            ],
            managers=[
                ('Objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='genrename',
            field=models.ForeignKey(blank=True, db_column='genrename', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='firstapp.genre'),
        ),
    ]
