# Generated by Django 4.1.5 on 2023-07-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='audiofilename',
        ),
        migrations.RemoveField(
            model_name='book',
            name='bookfilename',
        ),
        migrations.AddField(
            model_name='chapters',
            name='chapteraudiofilename',
            field=models.FileField(default=None, upload_to='./'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chapters',
            name='chapterfilename',
            field=models.FileField(default=None, upload_to='./'),
            preserve_default=False,
        ),
    ]
