# Generated by Django 4.1.5 on 2023-07-08 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_remove_book_audiofilename_remove_book_bookfilename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='emailiduploadedby',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='imagefilename',
            field=models.FileField(upload_to='./'),
        ),
    ]
