# Generated by Django 4.1.5 on 2023-07-10 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_alter_book_emailiduploadedby_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='feedback',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='userprogress',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='userprogress',
            old_name='chaptercompleted',
            new_name='chapterscompleted',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='id',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='id',
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedbackid',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprogress',
            name='progressid',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='playlist',
            fields=[
                ('playlistid', models.AutoField(primary_key=True, serialize=False)),
                ('addedon', models.DateField(blank=True, null=True)),
                ('bookcode', models.ForeignKey(blank=True, db_column='bookcode', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='firstapp.book')),
                ('usercode', models.ForeignKey(blank=True, db_column='usercode', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='firstapp.appusers')),
            ],
        ),
    ]
