# Generated by Django 4.1.5 on 2023-07-15 12:10

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_alter_feedback_managers_alter_userprogress_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='playlist',
            managers=[
                ('Objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='useremailid',
            new_name='usercode',
        ),
    ]
