# Generated by Django 4.1.5 on 2023-07-17 10:01

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_alter_playlist_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='requestbook',
            fields=[
                ('requestid', models.AutoField(primary_key=True, serialize=False)),
                ('requestdate', models.DateField(blank=True, null=True)),
                ('bookname', models.CharField(blank=True, max_length=30, null=True)),
                ('authorname', models.CharField(blank=True, max_length=30, null=True)),
                ('bookgenre', models.CharField(blank=True, max_length=30, null=True)),
                ('usercode', models.ForeignKey(blank=True, db_column='emailid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='firstapp.appusers')),
            ],
            managers=[
                ('Objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
